spring:
  data:
    mongodb:
      uri: mongodb+srv://apurbkumarchoudhary:Panther2a@cluster0.cvvivrn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

      